from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.loggin,name='loggin'),
    path('signup/',views.signup,name='signup'),
    path('wishlist/<int:product_id>/', views.wishlist, name='wishlist'),
    path('wishlists/',views.wishlists,name='wishlists'),
    path('casualfit/',views.casualfit,name='casualfit'),
    path('formalfit/',views.formalfit,name='formalfit'),
    path('innerwear/',views.innerwear,name='innerwear'),
    path('accessories/',views.accessories,name='accessories'),
    path('newarrivals/',views.newarrivals,name='newarrivals'),
    path('carts/<int:product_id>/', views.carts, name='carts'),
    path('cart/', views.cart, name='cart'),
    path("cart/increase/<int:id>/",views.increase_qty, name="increase_qty"),
    path("cart/decrease/<int:id>/",views.decrease_qty, name="decrease_qty"),
    path("cart/remove/<int:id>/",views.remove_cart, name="remove_cart"),
    path('forgot/',views.forgot,name='forgot'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('new_password/', views.new_password, name='new_password'),
    path('profile/',views.profile,name='profile'),
    path("editprofile/", views.editprofile, name="editprofile"),
    path('addaddress/',views.addaddress,name='addaddress'),
    path('address/delete/<int:id>/', views.delete_address, name='delete_address'),
    path('logout/',views.logout,name='logout'),
    path('order/',views.order,name='order'),
    path("orderdetails/<int:order_id>/", views.orderdetails, name="orderdetails"),
    path('adminpanel/',views.adminpanel,name='adminpanel'),
    path('adminproducts/',views.adminproducts,name='adminproducts'),
    path('adminorders/',views.adminorders,name='adminorders'),
    path("adminorders/status/<int:order_id>/", views.update_order_status, name="update_order_status"),
    path("adminorderdetails/<int:order_id>/", views.adminorderdetails, name="adminorderdetails"),    
    path('adminusers/',views.adminusers,name='adminusers'),
    path('adminusers/<int:user_id>/',views.block_unblock,name='block_unblock'),
    path('showlogin/',views.showlogin,name='showlogin'),
    path('productsedit/<int:id>/', views.productsedit, name='productsedit'),
    path('adminsettings/',views.adminsettings,name='adminsettings'),
    path('addproducts/',views.addproducts,name='addproducts'),
    path('editproducts/<int:id>/',views.editproducts,name='editproducts'),
    path('checkout/',views.checkout,name='checkout'),
    # path("payment/",views.payment,name="payment"),
    path('productsdelete/<int:id>/', views.productsdelete, name='productsdelete'),
    path('banner/',views.banner,name='banner'),
    path('productsdetail/<int:id>/', views.product_detail, name='productsdetail'),
    path('searchbutton',views.searchbutton,name='searchbutton'),
    path('product-toggle/<int:id>/', views.product_toggle, name='product_toggle'),
    path('addcategory/', views.add_category, name='add_category'),
    path('addsubcategory/', views.add_subcategory, name='add_subcategory'),
    path('admincategory/', views.admin_category, name='admin_category'),
    path('updatecategory/<int:id>/', views.update_category, name='update_category'),
    path('deletecategory/<int:id>/', views.delete_category, name='delete_category'),
    path('updatesubcategory/<int:id>/', views.update_subcategory, name='update_subcategory'),
    path('deletesubcategory/<int:id>/', views.delete_subcategory, name='delete_subcategory'),
    path("pay/", views.pay, name="pay"),
    path("placeorder/", views.place_order, name="place_order"),
    path("paymentsuccess/", views.payment_success, name="payment_success"),
    path("paymentfailed/", views.payment_failed, name="payment_failed"),
    path("buynow/<int:product_id>/", views.buy_now, name="buy_now"),
    path("reviewrating/<int:order_id>/", views.review_rating, name="review_rating"),
    path('deletereview/<int:review_id>/', views.delete_review, name='delete_review'),
    path('notifications/', views.notifications, name='notifications'),


]
