# Generated by Django 5.2.6 on 2026-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0002_products_featured_products_by_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='by_category',
        ),
    ]
