# Generated by Django 5.2.6 on 2026-01-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0003_remove_products_by_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Featured',
            new_name='trending',
        ),
    ]
