# Generated by Django 5.2.6 on 2026-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0004_rename_featured_products_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
