# Generated by Django 5.2.6 on 2026-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0005_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(to='clothing_store.size'),
        ),
    ]
