# Generated by Django 5.2.6 on 2026-01-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0006_size_remove_products_size_products_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('TOP', 'Top Wear'), ('BOTTOM', 'Bottom Wear')], default='TOP', max_length=10),
            preserve_default=False,
        ),
    ]
