# Generated by Django 5.2.6 on 2026-01-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0007_size_size_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='trending',
            new_name='is_trending',
        ),
    ]
