# Generated by Django 5.2.6 on 2026-02-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0011_category_has_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing_store.size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='clothing_store.size'),
        ),
    ]
