# Generated by Django 5.2.6 on 2026-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0013_alter_cart_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
