# Generated by Django 5.2.6 on 2026-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0016_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size_text',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
