# Generated by Django 5.2.6 on 2026-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
