# Generated by Django 5.2.6 on 2026-02-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0023_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
