# Generated by Django 5.2.6 on 2026-03-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0035_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
