# Generated by Django 5.2.6 on 2026-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='by_category',
            field=models.BooleanField(default=False),
        ),
    ]
