# Generated by Django 5.2.6 on 2026-01-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0003_rename_image_products_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image4',
            new_name='image',
        ),
    ]
