# Generated by Django 5.2.6 on 2026-01-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
