# Generated by Django 5.2.6 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0010_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_size',
            field=models.BooleanField(default=True),
        ),
    ]
