# Generated by Django 5.2.6 on 2026-01-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clothing_store', '0018_rename_user_table'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
