# Generated by Django 5.2.6 on 2026-01-23 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0019_rename_table_user_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlisted_by', to='clothing_store.products')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('User', 'Products')},
            },
        ),
    ]
