# Generated by Django 5.2.6 on 2026-03-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0027_alter_order_options_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quandity',
            new_name='quantity',
        ),
    ]
