# Generated by Django 5.2.6 on 2026-03-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0031_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='is_approved',
        ),
    ]
